FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Dummy URL for Prisma Client generation during build
ENV DATABASE_URL="postgresql://user:password@localhost:5432/dummy"

RUN npx prisma generate

RUN npm run build

EXPOSE 3001

CMD ["npm", "start"]